name: sign
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using flutter pub publish. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running flutter pub upgrade --major-versions. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run flutter pub outdated.
dependencies:
  flutter:
    sdk: flutter






  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  http: ^0.13.5
  gal: ^2.3.1
  url_launcher: ^6.3.1
  tflite_flutter: ^0.11.0
  image: ^3.3.0
  flutter_tts: ^3.5.2
  tflite_flutter_helper: ^0.2.1
  path_provider: ^2.1.2

dependency_overrides:
  tflite_flutter: ^0.11.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the analysis_options.yaml file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - images/logoo.webp
    - images/sup.png
    - images/A.jpg
    - images/number.png
    - images/num.jpg
    - images/1.jpg
    - images/2.jpg
    - images/3.jpg
    - images/4.jpg
    - images/5.jpg
    - images/6.jpg
    - images/7.jpg
    - images/8.jpg
    - images/9.jpg
    - images/aa.jpg
    - images/b.jpg
    - images/c.jpg
    - images/d.jpg
    - images/e.jpg
    - images/f.jpg
    - images/g.jpg
    - images/h.jpg
    - images/i.jpg
    - images/j.jpg
    - images/k.jpg
    - images/l.jpg
    - images/m.jpg
    - images/needs.webp
    - images/hi.png
    - images/indian.png
    - images/bye.png
    - images/again.png
    - images/me.png
    - images/man.png
    - images/woman.png
    - images/you.png
    - images/namaste.png
    - images/hearing.png
    - images/please.png
    - images/sorry.png
    - images/teacher.png


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

